_core:
  default_config_hash: gI_m_GxOGx9sRmt_8wOOtADorawijIRZqEiLPrhfOEo
show_url: true
results_heading: 'Test results'
output_placeholder: 'Test output will appear here...'
profile: performantlabs
region: us-east-1
function: atk-lambda-func-dev-execute_tests
cloudWatch:
  group: /custom/atk_logs
  timeout: 5000
s3:
  prefix: 'https://atk-playwright-results-79b8267d359c4c82bb9deae495980657.s3.us-east-1.amazonaws.com/'
drushCmd: 'export IS_DDEV_PROJECT=true && /var/www/html/vendor/bin/drush'
targetSite:
  isTarget: true
  host: 0.tcp.ngrok.io
  port: 13353
  username: ilya
tags:
  - '@alters-db'
  - '@ATK-PW-1000'
  - '@ATK-PW-1010'
  - '@ATK-PW-1011'
  - '@ATK-PW-1030'
  - '@ATK-PW-1050'
  - '@ATK-PW-1060'
  - '@ATK-PW-1061'
  - '@ATK-PW-1070'
  - '@ATK-PW-1071'
  - '@ATK-PW-1100'
  - '@ATK-PW-1101'
  - '@ATK-PW-1110'
  - '@ATK-PW-1111'
  - '@ATK-PW-1120'
  - '@ATK-PW-1130'
  - '@ATK-PW-1150'
  - '@ATK-PW-1160'
  - '@ATK-PW-1161'
  - '@ATK-PW-1162'
  - '@ATK-PW-1163'
  - '@ATK-PY-1012'
  - '@contact-us'
  - '@content'
  - '@drush'
  - '@empty'
  - '@media'
  - '@menu'
  - '@node'
  - '@page-error'
  - '@register-login'
  - '@search'
  - '@smoke'
  - '@taxonomy'
  - '@user'
  - '@xml-sitemap'
