pl_drupal_forge.settings:
  type: config_object
  label: 'PL Drupal Forge settings'
  mapping:
    show_url:
      type: boolean
      label: 'Show URL'
    output_placeholder:
      type: string
      label: 'Output placeholder text'
      default: 'Test output will appear here...'
